# =============================================================================
# CertiVault — DocumentDB Module
# =============================================================================
# Creates an Amazon DocumentDB (MongoDB-compatible) cluster with:
#   Subnet group       → pins cluster to private subnets
#   Security group     → allows port 27017 only from EKS node security group
#   Parameter group    → tuned for CertiVault workload
#   Cluster            → 1-node cluster (add instances for HA in production)
#   Cluster instance   → db.t3.medium (smallest billable DocumentDB instance)
#   Random password    → generated by Terraform, stored in AWS Secrets Manager
#
# NOTE: DocumentDB is NOT free-tier eligible. The smallest instance (db.t3.medium)
# costs ~$0.073/hr. Use this module for staging/production only.
# For local development, point MONGO_URI at MongoDB Atlas free tier instead.
#
# TLS: DocumentDB enforces TLS by default. The Node.js Mongoose connection
# string must include ?tls=true&tlsCAFile=<path-to-rds-ca-bundle>.
# Download the CA bundle:
#   curl -o rds-combined-ca-bundle.pem \
#     https://truststore.pki.rds.amazonaws.com/global/global-bundle.pem
# =============================================================================

locals {
  name = "${var.project_name}-${var.environment}"
}

data "aws_region" "current" {}
data "aws_caller_identity" "current" {}

# =============================================================================
# Random Password (stored in Secrets Manager, never in .tfstate plaintext)
# =============================================================================
resource "random_password" "docdb_master" {
  length           = 32
  special          = true
  override_special = "!#$%&*()-_=+[]{}<>:?" # characters safe in connection strings
}

resource "aws_secretsmanager_secret" "docdb_master" {
  name                    = "${var.project_name}/${var.environment}/docdb-master-password"
  description             = "DocumentDB master password for CertiVault ${var.environment}"
  recovery_window_in_days = 7

  tags = { Name = "${local.name}-docdb-master-secret" }
}

resource "aws_secretsmanager_secret_version" "docdb_master" {
  secret_id = aws_secretsmanager_secret.docdb_master.id
  secret_string = jsonencode({
    username = var.master_username
    password = random_password.docdb_master.result
    host     = aws_docdb_cluster.main.endpoint
    port     = aws_docdb_cluster.main.port
    dbname   = var.database_name
    uri      = "mongodb://${var.master_username}:${random_password.docdb_master.result}@${aws_docdb_cluster.main.endpoint}:${aws_docdb_cluster.main.port}/${var.database_name}?tls=true&retryWrites=false"
  })

  # Secret version must be created after the cluster endpoint is known
  depends_on = [aws_docdb_cluster.main]
}

# =============================================================================
# Subnet Group
# =============================================================================
resource "aws_docdb_subnet_group" "main" {
  name        = "${local.name}-docdb-subnets"
  subnet_ids  = var.subnet_ids
  description = "Private subnet group for CertiVault DocumentDB cluster"

  tags = { Name = "${local.name}-docdb-subnets" }
}

# =============================================================================
# Security Group
# =============================================================================
resource "aws_security_group" "docdb" {
  name        = "${local.name}-docdb-sg"
  description = "Allow MongoDB/DocumentDB access from EKS nodes only"
  vpc_id      = var.vpc_id

  tags = { Name = "${local.name}-docdb-sg" }
}

# Allow inbound port 27017 from each allowed security group (EKS nodes)
resource "aws_vpc_security_group_ingress_rule" "docdb_from_eks" {
  count                        = length(var.allowed_security_groups)
  security_group_id            = aws_security_group.docdb.id
  referenced_security_group_id = var.allowed_security_groups[count.index]
  from_port                    = 27017
  to_port                      = 27017
  ip_protocol                  = "tcp"
  description                  = "DocumentDB from EKS nodes"
}

# Allow all outbound
resource "aws_vpc_security_group_egress_rule" "docdb_egress" {
  security_group_id = aws_security_group.docdb.id
  cidr_ipv4         = "0.0.0.0/0"
  ip_protocol       = "-1"
}

# =============================================================================
# Parameter Group
# =============================================================================
resource "aws_docdb_cluster_parameter_group" "main" {
  family      = "docdb5.0"
  name        = "${local.name}-docdb-params"
  description = "CertiVault DocumentDB parameter group"

  # Enforce TLS — DocumentDB best practice
  parameter {
    name  = "tls"
    value = "enabled"
  }

  # Audit all DDL + DML operations (captured in CloudWatch Logs)
  parameter {
    name  = "audit_logs"
    value = "all"
  }

  tags = { Name = "${local.name}-docdb-params" }
}

# =============================================================================
# DocumentDB Cluster
# =============================================================================
resource "aws_docdb_cluster" "main" {
  cluster_identifier              = "${local.name}-docdb"
  engine                          = "docdb"
  engine_version                  = var.engine_version
  master_username                 = var.master_username
  master_password                 = random_password.docdb_master.result
  db_subnet_group_name            = aws_docdb_subnet_group.main.name
  vpc_security_group_ids          = [aws_security_group.docdb.id]
  db_cluster_parameter_group_name = aws_docdb_cluster_parameter_group.main.name
  port                            = 27017

  # Backups: keep 7 days, run at low-traffic window
  backup_retention_period      = var.backup_retention_days
  preferred_backup_window      = "02:00-03:00"
  preferred_maintenance_window = "sun:04:00-sun:05:00"

  # Storage encryption at rest
  storage_encrypted = true

  # Deletion protection — set to false only when decommissioning
  deletion_protection = var.deletion_protection

  # Enable CloudWatch log export for audit + profiler logs
  enabled_cloudwatch_logs_exports = ["audit", "profiler"]

  # Skip final snapshot only in non-production environments
  skip_final_snapshot       = var.environment != "production"
  final_snapshot_identifier = var.environment == "production" ? "${local.name}-docdb-final-snapshot" : null

  tags = { Name = "${local.name}-docdb" }
}

# =============================================================================
# DocumentDB Cluster Instance(s)
# =============================================================================
resource "aws_docdb_cluster_instance" "main" {
  count              = var.instance_count
  identifier         = "${local.name}-docdb-${count.index}"
  cluster_identifier = aws_docdb_cluster.main.id
  instance_class     = var.instance_class

  # Automatic minor version upgrades during maintenance window
  auto_minor_version_upgrade = true

  # Place instances across AZs for resilience when count > 1
  preferred_maintenance_window = "sun:04:00-sun:05:00"

  tags = { Name = "${local.name}-docdb-${count.index}" }
}
